### ISSUE TITLE
Cannot run EthercatMaster using Java 21

### ISSUE THREAD

**Issue by vrees** [ihmcrobotics/ihmc-soem-wrapper#17]
| Required Info | |
|---|---|
|Version or commit hash| actual develop branch - 0.15.0 |
|Operating System| Linux mint based on Ubuntu 24.04 LTS|
|JDK| openjdk version "21.0.4" 2024-07-16 |

####Steps to reproduce issue

Using current develop branch I compiled SOEM and compiled C library and SWIG wrapper and java library. The Spring Boot 3 Application using following EthercatMaster:

`
    public HeatpumpMaster(StateMachineWrapper stateMachineWrapper, Environment environment, AppSettings props) {
        super(environment, props);
       ....
    }
`

`public abstract class AbstractEcatMaster extends EtherCATRealtimeThread implements ApplicationRunner {
    public AbstractEcatMaster(Environment environment, AppSettings props) {
        super(
            props.getConfig().getNetworkInterface(),
            new PriorityParameters(PriorityParameters.getMaximumPriority()),
            new MonotonicTime(0, 1000000),
            true,
            100000
        );
        log.info("Using Network Interface={}", environment.getProperty("NETWORK_INTERFACE", props.getConfig().getNetworkInterface()));
    }
`

####Actual behavior
When starting the application following error is schown:
`
ined in file [/home/vrees/work/heatpump24/target/classes/de/vrees/heatpump/master/normal/HeatpumpMaster.class]: Failed to instantiate [de.vrees.heatpump.master.normal.HeatpumpMaster]: Constructor threw exception 
2024-10-01T08:29:32.169+02:00  INFO 54573 --- [  restartedMain] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled. 
2024-10-01T08:29:32.196+02:00 ERROR 54573 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed 

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'heatpumpMaster' defined in file [/home/vrees/work/heatpump24/target/classes/de/vrees/heatpump/master/normal/HeatpumpMaster.class]: Failed to instantiate [de.vrees.heatpump.master.normal.HeatpumpMaster]: Constructor threw exception
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:318)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:306)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1375)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1212)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:971)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:625)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)
	at de.vrees.heatpump.Heatpump24App.main(Heatpump24App.java:73)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:50)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.vrees.heatpump.master.normal.HeatpumpMaster]: Constructor threw exception
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:221)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:315)
	... 20 common frames omitted
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at us.ihmc.tools.nativelibraries.NativeLibraryLoader.getHash(NativeLibraryLoader.java:301)
	at us.ihmc.tools.nativelibraries.NativeLibraryLoader.extractLibraryWithDependenciesAbsolute(NativeLibraryLoader.java:99)
	at us.ihmc.tools.nativelibraries.NativeLibraryLoader.loadLibraryFromClassPath(NativeLibraryLoader.java:202)
	at us.ihmc.tools.nativelibraries.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:183)
	at us.ihmc.tools.nativelibraries.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:48)
	at us.ihmc.realtime.RealtimeNative.<clinit>(RealtimeNative.java:26)
	at us.ihmc.realtime.PriorityParameters.<clinit>(PriorityParameters.java:24)
	at de.vrees.heatpump.master.AbstractEcatMaster.<init>(AbstractEcatMaster.java:18)
	at de.vrees.heatpump.master.normal.HeatpumpMaster.<init>(HeatpumpMaster.java:34)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:208)
	... 22 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 35 common frames omitted
`

####Expected behavior
Application should not throw an exception while initializing PriorityParameters, EtherCATRealtimeThread 

####Contributors with relevant knowledge or expertise (optional)
It seems that javax/xml/bind is still used in one of the libs (probably ihmc-realtime) which was replaced by jakarta in Java 11

**Comment by vrees** [comment]
Fixed!
The problem was, that I used an old version of the **ihmc-native-library-loader** lib

Using following dependency it worked:
```
        <dependency>
            <groupId>us.ihmc</groupId>
            <artifactId>ihmc-native-library-loader</artifactId>
            <version>2.0.3</version>
        </dependency>
```
